language: java
jdk:
 - oraclejdk8
sudo: required
script: "mvn cobertura:cobertura"
before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2
notifications:
  slack:
    rooms:
      - momoments:xVrcfkDbzmNDfM7fqfo6tedx
    on_success: change
    on_failure: always
