language: java
jdk:
 - oraclejdk9
sudo: required
before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
cache:
  directories:
    - $HOME/.m2
notifications:
  slack:
    rooms:
      - momoments:xVrcfkDbzmNDfM7fqfo6tedx
    on_success: change
    on_failure: always
